# Generated by Django 6.0.6 on 2026-07-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adddepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddepartment',
            old_name='department_code',
            new_name='dep_code',
        ),
        migrations.RenameField(
            model_name='adddepartment',
            old_name='department_name',
            new_name='dep_name',
        ),
    ]
