# Generated by Django 6.0.6 on 2026-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_department_code_adddepartment_dep_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='dep_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
