# Generated by Django 6.0.6 on 2026-07-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_addemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addemp',
            old_name='designation',
            new_name='disignation',
        ),
    ]
