# Generated by Django 6.0.6 on 2026-07-16 10:34

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_designation_addemp_disignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemp',
            name='address',
            field=models.TextField(verbose_name=builtins.max),
        ),
    ]
