# Generated by Django 6.0.6 on 2026-07-18 03:45

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_addemp_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=50)),
                ('create_user', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=225)),
                ('current_user', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='upload_file')),
                ('description', models.CharField(verbose_name=builtins.max)),
                ('create_at', models.TimeField()),
            ],
        ),
    ]
