# Generated by Django 6.0.6 on 2026-07-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_fileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addemp',
            new_name='empadd',
        ),
    ]
