# Generated by Django 6.0.6 on 2026-07-18 17:54

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_addemp_empadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='addemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('department', models.CharField(max_length=500)),
                ('disignation', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='profile')),
                ('address', models.TextField(verbose_name=builtins.max)),
            ],
        ),
        migrations.DeleteModel(
            name='empadd',
        ),
    ]
