# Generated by Django 6.0.6 on 2026-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_fileupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
