# Generated by Django 6.0.6 on 2026-07-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_adminlogin_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminlogin',
            new_name='login',
        ),
    ]
