# Generated by Django 6.0.6 on 2026-07-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_adminlogin_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='create_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
