# Generated by Django 6.0.6 on 2026-07-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_adddepartment_create_at_alter_adddepartment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_History',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('File_no', models.CharField(max_length=225)),
                ('current_user', models.CharField(max_length=225)),
                ('forwarded_user', models.CharField(max_length=225)),
                ('action', models.CharField(max_length=225)),
                ('remark', models.CharField()),
                ('create_at', models.DateField()),
            ],
        ),
    ]
