# Generated by Django 6.0.6 on 2026-07-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_file_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminlogin',
            new_name='login',
        ),
    ]
