# Generated by Django 6.0.6 on 2026-07-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_adminlogin_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='adminlogin',
        ),
    ]
