# Generated by Django 6.0.6 on 2026-07-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_login_adminlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminlogin',
            new_name='login',
        ),
    ]
