# Generated by Django 6.0.6 on 2026-08-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemp',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file_history',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
