# Generated by Django 6.0.6 on 2026-08-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_addemp_address_alter_file_history_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='dep_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='dep_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='disignation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='emp_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
